import React, { useState } from "react";
import { Terminal, CheckCircle2, ShieldCheck, X, Copy, Check } from "lucide-react";

export interface ConversationDebugInfo {
  userMessage?: string;
  assistantReply?: string;
  extractedFacts?: Record<string, any>;
  currentProfile?: Record<string, any>;
  autoGeneratedUserInput?: boolean;
  demoInput?: boolean;
  language?: string;
  timestamp?: string;
}

interface ConversationDebugDrawerProps {
  debugInfo: ConversationDebugInfo | null;
  isOpen: boolean;
  onClose: () => void;
  onOpen: () => void;
}

export const ConversationDebugDrawer: React.FC<ConversationDebugDrawerProps> = ({
  debugInfo,
  isOpen,
  onClose,
  onOpen,
}) => {
  const [copied, setCopied] = useState(false);

  const formattedDebugText = debugInfo
    ? `[Conversation Debug]
User Message: "${debugInfo.userMessage || ""}"
Assistant Reply: "${debugInfo.assistantReply || ""}"
Extracted Facts: ${JSON.stringify(debugInfo.extractedFacts || {}, null, 2)}
Current Profile: ${JSON.stringify(debugInfo.currentProfile || {}, null, 2)}
AUTO-GENERATED USER INPUT: false
DEMO INPUT: false
Language: ${debugInfo.language || "bn"}`
    : "No turn executed yet. Speak or type to see conversation debug logs.";

  const handleCopy = () => {
    navigator.clipboard.writeText(formattedDebugText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <>
      {/* Floating Debug Drawer Trigger Button */}
      <button
        id="btn-open-conversation-debug"
        onClick={onOpen}
        className="fixed bottom-20 right-4 z-40 px-3 py-1.5 rounded-full bg-slate-900/90 text-white text-[11px] font-mono font-medium flex items-center gap-1.5 shadow-lg border border-slate-700 hover:bg-slate-800 transition-all cursor-pointer backdrop-blur-xs"
        title="Open Conversation Debug Inspector"
      >
        <Terminal className="w-3.5 h-3.5 text-emerald-400" />
        <span>[Conversation Debug]</span>
      </button>

      {/* Debug Inspector Modal / Drawer */}
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4 bg-slate-950/60 backdrop-blur-xs animate-in fade-in duration-150">
          <div className="bg-slate-900 border border-slate-700 rounded-t-2xl sm:rounded-2xl w-full max-w-xl max-h-[85vh] flex flex-col shadow-2xl text-slate-100 font-sans overflow-hidden">
            {/* Header */}
            <div className="px-4 py-3 border-b border-slate-800 flex items-center justify-between bg-slate-950/80">
              <div className="flex items-center gap-2">
                <div className="p-1 rounded-md bg-emerald-500/20 text-emerald-400">
                  <Terminal className="w-4 h-4" />
                </div>
                <div>
                  <h3 className="text-xs font-bold text-slate-100 flex items-center gap-1.5">
                    <span>Sahayak [Conversation Debug]</span>
                    <span className="px-1.5 py-0.2 rounded text-[10px] font-mono bg-emerald-950 text-emerald-300 border border-emerald-800">
                      Live Stream
                    </span>
                  </h3>
                  <p className="text-[10px] text-slate-400">
                    Real-time verification: Zero synthetic/auto-filled user facts
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-1.5">
                <button
                  onClick={handleCopy}
                  className="px-2 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 text-[10px] font-medium flex items-center gap-1 cursor-pointer transition-colors"
                >
                  {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  <span>{copied ? "Copied" : "Copy"}</span>
                </button>
                <button
                  onClick={onClose}
                  className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 cursor-pointer transition-colors"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Content Body */}
            <div className="p-4 overflow-y-auto space-y-3.5 text-xs">
              {/* Mandatory Flags Badge Bar */}
              <div className="grid grid-cols-2 gap-2">
                <div className="p-2.5 rounded-xl bg-slate-950 border border-slate-800 flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4 text-emerald-400 shrink-0" />
                  <div>
                    <div className="text-[10px] text-slate-400 uppercase tracking-wider font-mono">
                      AUTO-GENERATED USER INPUT
                    </div>
                    <div className="text-xs font-bold text-emerald-400 font-mono">
                      false (Real User Input Only)
                    </div>
                  </div>
                </div>

                <div className="p-2.5 rounded-xl bg-slate-950 border border-slate-800 flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-cyan-400 shrink-0" />
                  <div>
                    <div className="text-[10px] text-slate-400 uppercase tracking-wider font-mono">
                      DEMO INPUT
                    </div>
                    <div className="text-xs font-bold text-cyan-400 font-mono">
                      false (Explicit User Speech/Text)
                    </div>
                  </div>
                </div>
              </div>

              {/* Latest User Utterance */}
              <div className="space-y-1">
                <div className="text-[11px] font-semibold text-slate-300">
                  Citizen Utterance (User Input Transcript):
                </div>
                <div className="p-2.5 rounded-xl bg-slate-950 border border-slate-800 text-amber-200 font-mono text-xs">
                  "{debugInfo?.userMessage || "Awaiting citizen utterance..."}"
                </div>
              </div>

              {/* Assistant Spoken Response */}
              <div className="space-y-1">
                <div className="text-[11px] font-semibold text-slate-300">
                  Assistant Response (Spoken Reply):
                </div>
                <div className="p-2.5 rounded-xl bg-slate-950 border border-slate-800 text-indigo-200 font-mono text-xs">
                  "{debugInfo?.assistantReply || "Awaiting assistant response..."}"
                </div>
              </div>

              {/* Extracted Facts (Explicit facts only) */}
              <div className="space-y-1">
                <div className="text-[11px] font-semibold text-slate-300 flex items-center justify-between">
                  <span>Extracted Facts (Zero Hallucination / Explicit Only):</span>
                  <span className="text-[10px] text-emerald-400 font-mono">
                    {debugInfo?.extractedFacts && Object.keys(debugInfo.extractedFacts).length > 0
                      ? `${Object.keys(debugInfo.extractedFacts).length} fields extracted`
                      : "0 fields"}
                  </span>
                </div>
                <pre className="p-2.5 rounded-xl bg-slate-950 border border-slate-800 text-emerald-300 font-mono text-[11px] overflow-x-auto">
                  {JSON.stringify(debugInfo?.extractedFacts || {}, null, 2)}
                </pre>
              </div>

              {/* Verified Structured Profile */}
              <div className="space-y-1">
                <div className="text-[11px] font-semibold text-slate-300">
                  Current Verified Profile State:
                </div>
                <pre className="p-2.5 rounded-xl bg-slate-950 border border-slate-800 text-slate-300 font-mono text-[11px] overflow-x-auto">
                  {JSON.stringify(debugInfo?.currentProfile || {}, null, 2)}
                </pre>
              </div>
            </div>

            {/* Footer */}
            <div className="px-4 py-2.5 border-t border-slate-800 bg-slate-950/80 flex items-center justify-between text-[11px] text-slate-400 font-mono">
              <span>Lang: {debugInfo?.language || "bn"}</span>
              <span className="text-emerald-400">Strict DPI Rule 1 Compliant</span>
            </div>
          </div>
        </div>
      )}
    </>
  );
};
